config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :bookings, only: [:index]
  resources :lives, only: [:index]

  resources :lives, only: [:show, :create, :new] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :life
  belongs_to :renter, class_name: "User"

  validate :start_date_before_end_date

  private

  def start_date_before_end_date
    if start_date && end_date && start_date >= end_date
      errors.add(:base, "La date de début doit être inférieure à la date de fin")
    end
  end
end

app/models/life.rb
class Life < ApplicationRecord
  has_many :bookings, foreign_key: :life_id, dependent: :destroy
  has_one_attached :photo
  belongs_to :owner, class_name: "User"
  attr_accessor :street_number, :street_name, :city, :country

  validates :price_per_day, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :title, presence: true, length: { maximum: 40 }
  validates :job_title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lives, foreign_key: :owner_id
  has_many :bookings, foreign_key: :renter_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :birth_date, :street_number, :street_name, :country, presence: true
  validates :email, uniqueness: true, format: { with: /\A.*@.*\.com\z/ }
  validates :phone_number, format: { with: /\A(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}\z/ }
  validates :encrypted_password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    # il faut recuperer l'id du current id
    # il faut retourner tous les bookings dont le renter_id = user id
    @bookings = Booking.where(renter_id: current_user.id)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.renter_id = current_user.id
    @booking.life = Life.find(params[:life_id])

    if @booking.save
      redirect_to bookings_path, notice: 'Réservation créée avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @life = Life.find(params[:life_id])
    @booking = Booking.new
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :renter_id, :life_id)
  end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_life, only: [ :show ]
  before_action :set_user, only: [:edit, :update, :destroy]


  def index
    @lives = Life.all
    if params[:query].present?
      @lives = @lives.where("job_title ILIKE ?", "%#{params[:query]}%")
    end
  end

  def show
  end

  def new
    @life = Life.new
  end

  def create
    @life = Life.new(life_params)
    @life.owner_id = current_user.id
    @life.save

    if @life.save
      redirect_to lives_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_life
    @life = Life.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def life_params
    params.require(:life).permit(:title, :price_per_day, :description, :owner_id, :photo, :job_title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="card m-5 bg-info rounded-pill", style="opacity: 0.8;">
    <h1 class="text-center text- m-2 p-4">Votre historique de vie(s)</h1>
</div>

  <h2 class="container mt-4 mb-4">Vos expériences à venir:</h2>
    <% @bookings.each do |booking| %>
    <% owner = Life.find(booking.life_id).owner.id%>
      <% if booking.end_date >= Date.today%>
        <div class="container card-booking">
          <div class="image-life"><%= cl_image_tag Life.find(booking.life_id).photo.key,  width: 120, height: 120, crop: :fill %></div>
          <div class="card-booking-infos alignement">
            <div>
            <h2><%= Life.find(booking.life_id).job_title.titleize%></h2>
              <p>avec <%=User.find(owner).first_name%> <%=User.find(owner).last_name.first%>. du <%= booking.start_date%> au <%=booking.end_date%>.</p>
              <% number_of_days = (booking.end_date - booking.start_date).to_i %>
              <p class="total-price">Prix total: <%= (Life.find(booking.life_id).price_per_day * number_of_days).round %>€</p>
              </div>
                <% if booking.start_date > Date.today%>
                      <%= link_to booking_path(booking.id), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Etes vous sûr(e)s de vouloir annuler votre expérience?" } do %>
                      <i class="fa-solid fa-trash fa-3x mt-4" style="color: orange"></i>
                      <%end%>
                  <%end%>
          </div>
        </div>
      <%end%>
    <%end%>

  <h2 class="container mt-4 mb-4">Vos expériences passées:</h2>
  <% @bookings.each do |booking| %>
  <% owner = Life.find(booking.life_id).owner.id%>
    <% if booking.end_date < Date.today%>
      <div class="container card-booking opacity-25">
        <div class="image-life"><%= cl_image_tag Life.find(booking.life_id).photo.key,  width: 120, height: 120, crop: :fill %></div>
        <div class="card-booking-infos">
          <h2><%= Life.find(booking.life_id).job_title.titleize%></h2>
            <p>avec <%=User.find(owner).first_name%> <%=User.find(owner).last_name.first%>. du <%= booking.start_date%> au <%=booking.end_date%>.</p>
                <% number_of_days = (booking.end_date - booking.start_date).to_i %>
              <p class="total-price">Prix total: <%= (Life.find(booking.life_id).price_per_day * number_of_days).round %>€</p>
        </div>
      </div>
    <%end%>
  <%end%>

app/views/bookings/new.html.erb
<div class="container">
  <div class="card-create m-5 bg-primary rounded-pill" style="opacity: 0.7;">
    <% owner = Life.find(@life.id).owner_id %>
    <h1 class="text-center m-2 p-3 text-white">Testez votre nouvelle vie de
      <%= Life.find(@life.id).job_title.titleize %>
      avec <%= User.find(owner).first_name %> <%= User.find(owner).last_name.first %>.
    </h1>
  </div>

  <div class="mx-auto p-3 border rounded" style="max-width: 650px; font-size: 16px;">
    <%= simple_form_for [@life, @booking] do |f| %>
      <%= f.input :start_date, label: "Début", as: :string, input_html: { data: { controller: "datepicker" } }, style: "font-size: 14px;" %>
      <%= f.input :end_date, label: "Fin", as: :string, input_html: { data: { controller: "datepicker" } }, style: "font-size: 14px;" %>
      <p class="text-justify">Le prix total de votre expérience sera disponible depuis la page de vos réservations.</p>
      <%= f.button :submit, 'Valider ma réservation', class: 'btn btn-primary text-white rounded-pill', style: 'opacity: 0.7; font-size: 18px;' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnlife</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&family=PT+Sans&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/flatpickr.min.js"></script>
    <%= javascript_importmap_tags %>
</head>
<body>
  <% unless controller_name == 'pages' && action_name == 'home' %>
    <input type="checkbox" id="active">
    <label for="active" class="menu-btn"><i class="fas fa-bars"></i></label>
    <%= link_to lives_path, class: "logo btn btn-success", style: "text-decoration: none" do%>
    <span class="appli"><%= "AirbnLife " %><i class="fa-solid fa-hand-spock fa-bounce" style="color: #fdb465;"></i></span>
    <% end %>
    <div class="navbar">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Découvrir des vies", lives_path %></li>
          <li><%= link_to "Offrir ma vie", new_life_path %></li>
          <li><%= link_to "Mes réservations", bookings_path %></li>
          <li><%= link_to "Paramètres" %></li>
          <li><%= link_to "Me déconnecter", destroy_user_session_path, "data-turbo-method" => "delete" %></li>
        <% else %>
          <li><%= link_to "Me connecter", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
    <%= render "shared/flashes" %>
  <% end %>
    <%= yield %>
  <% unless controller_name == 'pages' && action_name == 'home' || controller_name == 'bookings' && action_name == 'new' || controller_name == 'lives' && action_name == 'new' %>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
  <div class="footer-copyright">
    <%= "AirbnLife " %><i class="fa-solid fa-hand-spock fa-bounce" style="color: #fdb465;"></i></span>
<%end%>
  </div>
</div>
</body>
</html>

app/views/lives/create.html.erb
<h1>Valider</h1>
<p>Find me in app/views/lives/create.html.erb</p>

app/views/lives/index.html.erb
<div class=" row justify-content-center mt-1">
  <div class="col-5">
    <%= form_with url: lives_path, method: :get, class: "d-flex search-bar" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Prêt(e) pour une nouvelle vie ?"
        %>
      <%= button_tag(type: "submit", class: "btn btn-success") do %>
       <i class="fa-solid fa-magnifying-glass" style="color: #f5f5f5;"></i>
      <% end %>
    <% end %>
  </div>
</div>

<div class="card m-5 bg-success rounded-pill">
    <h1 class="text-center text-white m-2 p-4">Découvrez votre nouvelle vie avant de l'adopter!</h1>
</div>

<div class="cards-container">
  <% @lives.each do |life| %>
    <div class="box">
      <div class="imgBox">
        <%= link_to life_path(life), class: 'life-link' do %>
          <%= cl_image_tag life.photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
      </div>
      <div class="content">
        <h2><%= life.job_title.titleize %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/lives/new.html.erb
<div class="container">
  <div class="card-create m-5 bg-warning rounded-pill" style="opacity: 0.7;">
    <h1 class="text-center m-2 p-3 text-white">Offrir ma vie à louer</h1>
  </div>

  <div class="mx-auto p-3 border rounded" style="max-width: 600px; font-size: 16px;">
    <%= simple_form_for @life, html: { multipart: true } do |f| %>
      <%= f.input :job_title, label: "Métier", input_html: { style: "font-size: 14px;" } %>
      <%= f.input :title, label: "Titre de votre annonce", input_html: { style: "font-size: 14px;" } %>
      <%= f.input :price_per_day, label: "Prix par jour", input_html: { style: "font-size: 14px;" } %>
      <%= f.input :description, label: "Description de votre annonce", input_html: { style: "font-size: 14px;" } %>
      <%= f.input :photo, as: :file, input_html: { style: "font-size: 14px;" } %>

      <div class="text-left font-weight-light mt-3">
        <small class="form-text text-muted">Champs obligatoires: ...*</small>
      </div>

      <div class="text-center mt-4">
        <%= f.submit 'Valider ma vie', class: 'btn btn-warning text-white rounded-pill', style: 'opacity: 0.7; font-size: 18px;' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lives/show.html.erb
<div class="container card-life">
  <div class="image-life"><%= cl_image_tag @life.photo.key, width: 500, height: 600, crop: :fill %>
  </div>
  <div class="card-life-infos">
    <div>
      <h2 class="text-center"><%= @life.title %></h2>
        <% user = User.find(@life.owner_id) %>
        <p class="user-infos text-center"><%= user.first_name %> <%= user.last_name.first %>. - <%= user.age %> ans - de <%= user.city %>, <%= user.country %></p>
      </div>
      <div>
        <h3 class="pt-5 text-center">Pourquoi devenir <%= @life.job_title.titleize %> ?</h3>
        <p class="life-description"><%= @life.description %></p>
      </div>
        <div class="d-flex align-items-end justify-content-between">
          <div class="price"><strong>Prix à la journée : <%= number_to_currency(@life.price_per_day, unit: '€') %></strong></p></div>
          <%= link_to new_life_booking_path(@life), class: "btn btn-info bottom-right-btn" do %>
             <span> Devenez <%= @life.job_title.titleize %> <i class="fa-solid fa-face-smile-beam fa-bounce" style="color: #347347;"></i> </span>
          <%end%>
        </div>
  </div>
</div>


<%= link_to lives_path, class: "index-page btn btn-success", style: "text-decoration: none" do%>
     <span><i class="fa-solid fa-arrow-left fa-beat-fade" style="color: #fdb465;"></i> <%="Retour aux vies"%> </span></span>
<% end %>

app/views/pages/home.html.erb
<div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1527856263669-12c3a0af2aa6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80)">
  <div class="banner-container fixed-bottom bottom-center">
    <h1>Testez vos vies avant de les adopter, grâce à <%= link_to lives_path, class: "btn btn-success", style: "text-decoration: none" do%>
      <span class="appli"><%= "AirbnLife " %><i class="fa-solid fa-hand-spock fa-bounce" style="color: #fdb465;"></i></span>
      <% end %>
    <p>Explorez l'infini des possibles: pourquoi vivre une seule <strong>vie</strong>, quand on peut en avoir <strong>plusieurs</strong>?</p>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>